### ISSUE TITLE
StringTest=double not handled gracefully by chart title

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/neuron#103]
The chart title overlaps with the clear button. The chart title should scale down in font size if it gets too long (perhaps if it is going to violate the space of the Clear button?

![neuron](https://cloud.githubusercontent.com/assets/4051174/11988068/1951ab5c-a9a7-11e5-96fc-efacd7eb99f7.PNG)

**Comment by jbphet** [comment]
Fixed in both the master and 1.0 branches by adding a ```maxWidth``` to the title and making some other adjustments.  Chart for ```stringTest=double``` now looks like this:

![neuron-chart-double-strings](https://cloud.githubusercontent.com/assets/3082831/12098626/9b079f0c-b2e0-11e5-95e6-ecf093e1b804.png)

For ```stringTest=long``` it looks as shown in the following screen capture.  The Clear button is very short, but setting a min height wasn't working as expected, and the caption is ridiculously long anyway, so I don't believe that this will be a problem in the real world.

![neuron-chart-long-strings](https://cloud.githubusercontent.com/assets/3082831/12098667/d5ab0fc2-b2e0-11e5-8bc1-ccd976c2687e.png)

**Comment by jbphet** [comment]
Fix should appear in v1.0.0-rc.2, leaving open until verified on that release.

**Comment by jbphet** [comment]
Assigning to @ariel-phet so that he or someone on the QA team can verify that this is fixed on v1.0.0-rc.2 (http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.2/neuron_en.html).

**Comment by ariel-phet** [comment]
Made checklist item for https://github.com/phetsims/tasks/issues/485

**Comment by elisemorgan** [comment]
This issue has been resolved
