### ISSUE TITLE
Performance optimization may be required to run well on iPads

### ISSUE THREAD

**Issue by samreid** [phetsims/neuron#55]
@jbphet said:

> I just tested the fallback for WebGL to Canvas on my iPad 2 for Neuron, and results aren’t good, and we’ll need to decide where to go from here.  As a data point, when you have a chance, could you try ?profiler on the current master version of Neuron and let me know what frame rate you see?

> BTW, I know you’ve upgraded your iPad 3 to iOS 8 – I just want to see what the performance is like in that environment.

> Actually, best would be to do both without the flag (i.e. using WebGL) and with the flag (thus using canvas).

**Comment by jbphet** [comment]
Due to work on #65, Neuron is now working with Scenery 0.2 and WebGL.  I've published the first working version with these combinations so that we can quantify performance and use it as a baseline against which to measure the efficacy of optimizations.  This version can be found at http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.11/neuron_en.html.

Performance numbers below were measured using the "profiler" query parameter and looking at the frame rate for 10 successive samples and averaging the result.  In some cases, the lowest value seen was also recorded.

On an iPad 2 (model A1395) running iOS 8.3, the performance is as follows:
+ default zoom, no action potential: 57.8 fps
+ default zoom, action potential at the cross section and additional particles crossing the membrane: 19.1 fps
+ default zoom, action potential at the cross section and additional particles crossing the membrane, lowest frame rate was 16 fps
+ zoomed in about 3/4 of the way such that five membrane channels are showing (see screenshot below), no action potential: 59.6 fps
+ zoomed in about 3/4 of the way such that five membrane channels are showing (see screenshot below), action potential at cross section and particles crossing membrane: 30 fps
+ zoomed in about 3/4 of the way such that five membrane channels are showing (see screenshot below), action potential at cross section and particles crossing membrane, lowest frame rate: 20 fps

On iPad 3 model A1416 (Disessa) running iOS 8.3 (12F69)
+ default zoom, no action potential: 57.9 fps
+ default zoom, action potential at the cross section and additional particles crossing the membrane: 19.3 fps
+ default zoom, action potential at the cross section and additional particles crossing the membrane, lowest frame rate was 17 fps
+ zoomed in about 3/4 of the way such that five membrane channels are showing (see screenshot below), no action potential: 59.8 fps
+ zoomed in about 3/4 of the way such that five membrane channels are showing (see screenshot below), action potential at cross section and particles crossing membrane: 25.1
+ zoomed in about 3/4 of the way such that five membrane channels are showing (see screenshot below), action potential at cross section and particles crossing membrane, lowest frame rate: 21

![neuron-zoomed](https://cloud.githubusercontent.com/assets/3082831/9183533/e6ef75e4-3f6c-11e5-9991-f269a83c68f3.PNG)

**Comment by jbphet** [comment]
I've implemented an optimization in the WebGL particle node where the intermediate particle data is allocated once at sim initialization and updated, rather than reallocated, on each repaint.  I ran four trials before and after this change, and the percentage of time spent idle increased 1.52%.  It's not a lot, but every little bit helps.  Link to commit: cad55ed2ac2374ad6a3520fda7847ab142828c91

**Comment by jbphet** [comment]
I implemented a change where the EventTimer used by NeuronClockModelAdapter is not clocked by the dt amount and not a fixed amount.  It seems to me that this is the way it should have been done initially, else long dt values could lead to slow performance of the sim (which is exactly what was being seen).  This change makes iPad behavior way better.  Strictly speaking, this isn't really an optimization, it's more of a fix, so I didn't mention this issue in the commit message.  For future reference, this is the commit: 3dae114c32da471afee78565ec1c8374fb9ce56f.

**Comment by jbphet** [comment]
I demoed version 1.0.0-dev.12 (http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.12/) on an iPad 3 at today's status meeting.  @ariel-phet said that the performance of particle motion is adequate.  I'm still going to try a couple more optimizations that I think will help, but then will move on to speeding up the zoom in/out.

**Comment by jbphet** [comment]
Assigning to @ariel-phet so that he or someone on the QA team can verify that performance is acceptable on v1.0.0-rc.2 (http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.2/neuron_en.html).

**Comment by ariel-phet** [comment]
Zooming is very smooth. 

I would not classify performance as the "buttery smooth" level on iPad2 for stimulating, however, any stutters are generally minor enough to not raise fear of causing any pedagogical difficulties. I think most people will not even notice. Performance deemed acceptable. Closing
