### ISSUE TITLE
"All Ion" check box and "Stimulate Neuron" button behavior inconsistencies

### ISSUE THREAD

**Issue by phet-steele** [phetsims/neuron#57]
1. Check the "Potential Chart" option.
2. Stimulate the neuron and watch the chart as the sim plays while noting the time when "Stimulate Neuron" and "All Ions" are no longer grayed out (they went gray when you clicked "Stimulate Neuron"). This will most likely happen around 12 seconds.
3. Let the sim play for awhile after the time you noted, maybe to 20 seconds for example. During this time you've waited notice that "Stimulate Neuron" and "All Ions" are still click-able.
4. Pause the sim, and either click the step back button or drag the line on the chart to a time after the time you noted in step 2 but before the time you waited until in step 3.
5. Play the sim.
6. Notice now that "Stimulate Neuron" and "All Ions" have become grayed out, even though during this original time interval of between 12 and 20 seconds they were click-able.

Troubleshooting information:
Name: Neuron
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.7/neuron_en.html
Version: 1.0.0-dev.7
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jbphet** [comment]
With regard to the "Stimulate Neuron" button, I think that the current behavior makes perfect sense, since we can't have the users stimulating the neuron during playback.  However, it is a bit odd that the "All Ions" check box doesn't behave exactly like the other check boxes, since its state isn't recorded anyway (I checked this by turning it off once a stimulate cycle completed, then doing a playback).

I've verified that the identified behavior is consistent with the Java version of the Neuron sim, so it wasn't introduced during the port.  I'll look into the code and see if there is any obvious reason why the "All Ions" checkbox can't be enabled all the time.

**Comment by jbphet** [comment]
I just discussed this with @ariel-phet, and we agreed to try decoupling the enabled state of the "All Ions" checkbox from the playback state.

**Comment by jbphet** [comment]
I tried decoupling the enabled state of the "All Ions" check box from the playback state, and it didn't work.  I dug into it a bit, and now recall why the disabling of this button during action potentials was done.  When the "All Ions" value is set, a bunch of randomly positioned ions are added to the model.  If one of these happens to end up near a gate, it should pass through that gate as either part of the leakage flow or during an action potential.  If all ions are NOT shown, all of the ions needed to depict the appropriate flow are created as needed.  Handling the situation where the ions pop into existence part way through an action potential would be tricky, and would probably look weird, hence the lockout.

Since the initial behavior is now better understood, and since no one ever complained about it for the Java sim, and since it would be hard to change, I highly recommend closing this as "won't fix".  Assigning to @ariel-phet to make sure he concurs.  If so, he can just close it.
