### ISSUE TITLE
branch: pixi-webgl

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/neuron#70]
Please describe.

**Comment by samreid** [comment]
Uses scenery nodes instead of CanvasNode for drawing particles so we can experiment with different scenery renderers such as pixi.

**Comment by jbphet** [comment]
@samreid - I'm working on a WebGL implementation for rendering the particles and don't expect to experiment with pixi or any other renderers, at least not any time soon.  Shall we delete this branch?  I'm okay with keeping it if you believe that it has value - just leave it unassigned if so since I don't think either of us has any plans to work on it in the short term.

**Comment by samreid** [comment]
Please delete it, if we resume work with pixi (which is unlikely) we would start with a different version of pixi and in a different context.

**Comment by jbphet** [comment]
Deleted, closing.
