### ISSUE TITLE
Membrane channel gates are not always reset when Reset All is pressed

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#89]
If the Reset All button is pressed when the dynamic sodium and/or potassium membrane channels are open, they are not always properly reset.  This issue is visible on the current master and the most recent dev release, which is http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.13/neuron_en.html.  It is probably present on other dev versions too, but hasn't been tested.

**Comment by orejolaphet** [comment]
I went through the dev versions. This issue has been present since http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.3/neuron_en.html
<img width="580" alt="screen shot 2015-10-13 at 10 17 10 am" src="https://cloud.githubusercontent.com/assets/5631059/10460857/aa150c16-7193-11e5-9dea-0cf7e6c464c4.png">

Screenshot from http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.13/neuron_en.html
<img width="708" alt="screen shot 2015-10-13 at 10 13 04 am" src="https://cloud.githubusercontent.com/assets/5631059/10460862/b929edc0-7193-11e5-9e0f-3bb84954fbaf.png">

**Comment by jbphet** [comment]
There were actually two problems that were causing this behavior.  The first was that the reset of the membrane channels wasn't being conveyed to the view in some circumstances, so the view wasn't being updated.  The second was that the DelayBuffer had a subtle bug that would cause it to provide old data after being cleared.  Both of these issues have been addressed.  Closing.
